Principal:
    name: 'inicio'

    FloatLayout:
        size_hint: (1, 1)

        Image:
            source: 'foto.jpg'
            allow_stretch: True
            keep_ratio: False



        FloatLayout:
            size_hint: (1, 1)
            id: scroll

    MDFloatingActionButton:
        pos_hint: {'x': 0.42, 'y': 0.05}
        md_bg_color: "yellow"
        icon: "plus"
        text_color: "black"

        on_press:
            root.novo_item()